version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - DataVolume1:/code
            - ./config/nginx:/etc/nginx/conf.d
            - ./fastcgi.conf:/etc/nginx/fastcgi.conf
        links:
            - php56
            - php70
        depends_on:
            - php56
            - php70
    php56:
        build:
           context: ./ 
           dockerfile: ./DockerfilePhp56
        volumes:
           - DataVolume1:/code
        restart: always
    php70:
        build:
            context: ./ 
            dockerfile: ./DockerfilePhp70
        volumes:
            - DataVolume1:/code
        restart: always
        links:
            - db
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
         - PMA_ARBITRARY=1
        restart: always
        ports:
         - 8080:80
        links:
            - db
        depends_on:
            - db
    db:
        image: mysql
        restart: always
        #ports:
        #    - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
    ssh:
        build:
           context: ./
           dockerfile: ./DockerfileSsh
        volumes:
           - DataVolume1:/code
        restart: always
        ports:
           - "2200:22"
volumes:
  DataVolume1:
