web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./code:/code
        - ./conf.d:/etc/nginx/conf.d
    links:
        - php
php:
    build: ./
    volumes:
        - ./code:/code
