version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./code:/code
            - ./conf.d:/etc/nginx/conf.d
            - ./fastcgi.conf:/etc/nginx/fastcgi.conf
        links:
            - php
    php:
        build: ./
        volumes:
            - ./code:/code
        restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
         - PMA_ARBITRARY=1
        restart: always
        ports:
         - 8080:80
        #links:
        # - db:db
        #depends_on:
        #    - db
    #db:
        #image: mysql
        #restart: always
        #ports:
        #    - "3307:3306"
        #environment:
        #    MYSQL_ROOT_PASSWORD: root
        #volumes:
        #    - ./code:/code

